"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from .allowed_hosts import *
from .databases import *
from .debug import *
from .i18n import *
from .installed_apps import *
from .logging import *
from .middleware import *
from .password import *
from .secret_key import *
from .static import *
from .templates import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# Application definition

ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INTERNAL_IPS: list[str] = []
