# Generated by Django 4.1.2 on 2022-10-24 02:11

import django.db.models.deletion
from django.db import migrations, models

import aria2.models.aria2c


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aria2c",
            fields=[
                (
                    "path",
                    aria2.models.aria2c.PathField(
                        max_length=256, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Aria2c - Binary",
                "verbose_name_plural": "Aria2c - Binaries",
            },
        ),
        migrations.CreateModel(
            name="Aria2cArgumentTag",
            fields=[
                (
                    "value",
                    models.CharField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Aria2c - Argument Tag",
            },
        ),
        migrations.CreateModel(
            name="Aria2cArgument",
            fields=[
                (
                    "short_argument",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "long_argument",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=256)),
                (
                    "possible_values",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("default", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "aria2c",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aria2.aria2c"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="aria2.aria2cargumenttag"),
                ),
            ],
            options={
                "verbose_name": "Aria2c - Argument",
            },
        ),
        migrations.CreateModel(
            name="Aria2cInstance",
            fields=[
                ("pid", models.IntegerField(primary_key=True, serialize=False)),
                ("command", models.CharField(max_length=256, unique=True)),
                (
                    "aria2c",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aria2.aria2c"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aria2c - Instance",
            },
        ),
    ]
